### ISSUE TITLE
excluder: checks for exclusion criteria in online data

### ISSUE THREAD

**Issue by JeffreyRStevens** [ropensci/software-review#455]
**Date accepted:** 2021-11-04
Submitting Author Name: Jeffrey Stevens
Submitting Author Github Handle: @JeffreyRStevens
Repository:  https://github.com/JeffreyRStevens/excluder
Version submitted: 0.2.2
Submission type: Standard
Editor:  @maurolepore 
Reviewers:  @juliasilge, @jmobrien
Due date for @juliasilge: 2021-09-20
Due date for @jmobrien: 2021-09-20
Archive: TBD
Version accepted: TBD

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: excluder
Title: Checks for Exclusion Criteria in Online Data
Version: 0.2.2
Authors@R: 
    person(given = "Jeffrey R.",
           family = "Stevens",
           role = c("aut", "cre"),
           email = "jeffrey.r.stevens@gmail.com",
           comment = c(ORCID = "0000-0003-2375-1360"))
Description: Data that are collected through online sources such as Mechanical 
            Turk may require excluding data because of IP address duplication, 
            geolocation, or completion duration. This package facilitates
            exclusion of these data for Qualtrics datasets.
License: GPL (>= 3)
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.1
URL: https://jeffreyrstevens.github.io/excluder/, https://github.com/jeffreyrstevens/excluder/
BugReports: https://github.com/jeffreyrstevens/excluder/issues/
Imports: 
    dplyr,
    iptools,
    janitor,
    lubridate,
    maps,
    tidyr,
    magrittr,
    rlang
Depends: 
    R (>= 3.5.0)
Suggests: 
    testthat (>= 3.0.0),
    readr,
    stringr,
    covr,
    knitr,
    rmarkdown,
    lifecycle
Config/testthat/edition: 3
VignetteBuilder: knitr
```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] data extraction
	- [X] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):

The package falls under data munging because it processes data from Qualtrics or other online sources by checking for, marking, and excluding rows of data frames for common exclusion criteria (e.g., IP addresses outside of the United States or duplicate entries from the same location/IP address).

-   Who is the target audience and what are scientific applications of this package?

The target audience is data scientists using Qualtrics or other online systems to collect data from participants (e.g., Mechanical Turk workers). Ensuring good data quality from these participants can be tricky. For instance, while Mechanical Turk in theory screens workers based on location (e.g., if you want to restrict your participant pool to workers in the United States), this is not necessarily represented in the data. Finding the tools to screen for IP address location can be tricky, and this package simplifies checking for and excluding participants based on common data that Qualtrics reports such as geolocation, IP address, duplicate records from the same location, participant screen resolution, participant progress through the survey, and survey completion duration.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

There are no similar packages to my knowledge. The {qualtRics} package at rOpenSci focuses on importing data from Qualtrics. The {MTurkR} package directly interfaces with the MTurk Requestor API, but the APIs have been deprecated and the package has been removed from CRAN.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

Yes, it seems to comply with this guidance. Depending on the data that the user collects, there could be personally identifiable information accessed by this package. In particular, IP addresses that are recorded by Qualtrics can be processed with this package. Note that the package only works with personally identifiable information from data sets that already exist on the users' local file system, and the package does not collect or transmit data in any way. The package also includes a function `deidentify()` that the user can use to strip location, IP address, language and even participant computer information (e.g., operating system, web browser, screen resolution) from the data frames to deidentify them.

-   If you made a pre-submission inquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

https://github.com/ropensci/software-review/issues/454

## Technical checks

Confirm each of the following by checking the box.

- [X] I have read the [guide for authors](https://devguide.ropensci.org/guide-for-authors.html) and [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).

This package:

- [X] does not violate the Terms of Service of any service it interacts with.
- [X] has a CRAN and OSI accepted license.
- [X] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [X] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [X] contains a vignette with examples of its essential functions and uses.
- [X] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [X] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [X] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [X] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) during the review process and in maintaining my package should it be accepted.

**Comment by noamross** [comment]
@ropensci-review-bot check package

**Comment by JeffreyRStevens** [comment]
The only check that failed was "Package does not have a 'contributing.md' file". Does this mean that the package should **not** have a contributing.md file? So should I just remove the file and remove all references to Contributing to this package?

**Comment by noamross** [comment]
Thanks for the submission @JeffreyRStevens! Sorry for a bit of a delay as we were working out our new automated diagnostics bot, which your review is the first to use, and you just found a bug in! Your `CONTRIBUTING.md` file is fine, we are just failing to check the right subfolder.  We'll move ahead with this :)

**Comment by JeffreyRStevens** [comment]
Ah, OK--no problem. Glad to be a guinea pig to help debug!

**Comment by maurolepore** [comment]
@JeffreyRStevens, it's my pleasure to be the handling editor of your submission. 

### Editor checks:

- [x] **Documentation**: The package has sufficient documentation available online (README, pkgdown docs) to allow for an assessment of functionality and scope without installing the package.
- [x] **Fit**: The package meets criteria for [fit](https://devguide.ropensci.org/policies.html#package-categories) and [overlap](https://devguide.ropensci.org/policies.html#overlap)
- [x] **Automated tests:** Package has a testing suite and is tested via a CI service.
- [x] **License:** The package has a CRAN or OSI accepted license
- [x] **Repository:** The repository link resolves correctly

---

#### Editor comments


Congratulations! The bot and I are very happy to see the package meets rOpenSci's guidelines :+1:. I'll start looking for reviewers. 

Note the following minor issues. You might want to consider before the review:

* `devtools::check()` shows:

```r
❯ checking Rd cross-references ... NOTE
  Packages unavailable to check Rd xrefs: ‘qualtRics’, ‘rgeolocate’
```

* `check_deduplicate()` seems to have a relatively complex logic. It may be justified by the goal of the function (to check for various conditions) but might be worth ensuring there is no more logic than necessary.

* Some `if()` statements seem fragile as they could get inputs of length greater than 1. Consider the argument `dupl_ip` to `check_duplicates()`:

``` r
# Good
dupl_ip <- TRUE
if (identical(dupl_ip, TRUE)) {
  message("Do something.")
}
#> Do something.

# Good
dupl_ip <- TRUE
stopifnot(length(dupl_ip) == 1L)
if (dupl_ip) {
  message("Do something.")
}
#> Do something.

# Fragile
dupl_ip <- c(TRUE, FALSE)  # This might be accidentally non-atomic
if (dupl_ip == TRUE) {
  message("Do something.")
}
#> Warning in if (dupl_ip == TRUE) {: the condition has length > 1 and only the
#> first element will be used
#> Do something.
```

<sup>Created on 2021-08-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

* Some lines are longer than 80 characters. Wrapping at 80 characters makes the code easier to review, without having to scroll right when navigating the script.

* I see two methods to avoid the R CMD check NOTE about undefined global variables: `var <- NULL` ([e.g.](https://github.com/JeffreyRStevens/excluder/blob/1d8446c90ca467b8257592230a7b0abc8f348c48/R/collapse_exclusions.R#L45)) and [`.data$var`](https://github.com/JeffreyRStevens/excluder/blob/1d8446c90ca467b8257592230a7b0abc8f348c48/R/collapse_exclusions.R#L55). Maybe best to use only one method?

* In R/ I see a subdirectory (R/deprecated). I find this strange. How is it used?

* `devtools::test()` shows:

```r
check-mark-exclude: 
Note: Using an external vector in selections is ambiguous.
i Use `all_of(location_col)` instead of `location_col` to silence this message.
i See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>.
```

* The structure of the tests impairs the use of the convenient workflow with `usethis::use_r()` and `usethis::use_test()`. Consider structuring tests so that for each exported `fun()` in R/fun.R you have a test in tests/testthat/test-fun()`.


---

Reviewers: TBC
Due date:

**Comment by maurolepore** [comment]
@ropensci-review-bot seeking reviewers

**Comment by maurolepore** [comment]
@JeffreyRStevens, could you suggest two or three potential reviewers? Although I wouldn't pick more than one, your list will inform the type of expertise you think would be useful when reviewing {excluder}. 

I'll also use other criteria as described in [How to look for reviewers](https://devdevguide.netlify.app/editorguide.html?#look-for-and-assign-reviewers).

**Comment by JeffreyRStevens** [comment]
@maurolepore thank you for your speedy initial review of {excluder}. I have pushed some changes to address your comments.
* In running `usethis::check()`, I am not able to replicate your error regarding `Packages unavailable to check Rd xrefs: ‘qualtRics’, ‘rgeolocate’`. Would you mind checking if this is still an issue in the new version? If so, does this mean that you need to have the packages installed on your local machine to pass the check?
* I'm not sure if it is possible to simplify the logic of `check_duplicates()`. I'm open to ideas from you or the reviewers, though. 
* Regarding the fragile `if()` statements, are you suggesting that I check if the `dupl_id` argument is identical to TRUE or of length 1. And, if so, I assume you'd like me to look at other `if()` statements to see if the same issue applies? Just want to clarify the action items for this issue.
* I trimmed lines longer than 80 characters. The remaining lines > 80 characters are primarily messages/warnings or tests. Should I break those across multiple lines? Is the aim to reduce the number of lines > 80 or minimize the number of characters > 80? For example, in `remove_label_rows.R` lines [53-59](https://github.com/JeffreyRStevens/excluder/blob/d99bc23850c3f6f7ae3001cf0b94324b9e0a827b/R/remove_label_rows.R#L53), I broke this over multiple lines to minimize characters > 80, but it resulted  in severa lines slightly larger that 80 characters rather than just line much larger. Which is preferred?
* Regarding undefined global variables, I used `exclusions <- NULL` in `collapse_exclusions.R` because I can't figure out how to use `.data` in a way to avoid the R CMD note. If I use `.data$exclusions` to replace `exclusions` in the `unite()` function (line [55](https://github.com/JeffreyRStevens/excluder/blob/d99bc23850c3f6f7ae3001cf0b94324b9e0a827b/R/collapse_exclusions.R#L55)) or the column definition in the `mutate()` function (line [60](https://github.com/JeffreyRStevens/excluder/blob/d99bc23850c3f6f7ae3001cf0b94324b9e0a827b/R/collapse_exclusions.R#L60)), I receive a compiling error when running the check. The current version has removed the `exclusions <- NULL`, which results in the R CMD note. One option would be to reinsert the `NULL` definition and remove all `.data` from this particular function. But would I need to replace all `.data` with `NULL` definitions in all functions or just this one?
* LOL--the directory _R/deprecated_ was supposed to be added to the `.gitignore` file. It has now been removed. 
* I have addressed the `all_of(location_col)` warning in the test.
* I have restructured the tests to have a test for each function.
* I have added the rOpenSci peer review badge to the README.
* Two potential reviewers would be the authors of {qualtRics}: Julia Silge and Jasper Ginn.

Thank you again for your careful review, and let me know if I missed something.

**Comment by maurolepore** [comment]
Thanks @JeffreyRStevens for responding quickly.

* Yes, I still see that R CMD NOTE and two more. FYI I updated all my packages then run `devtools::check()`. Here is a reprex -- collapsed to save space.

<details style="margin-bottom:10px;">
<summary>
Output
</summary>

``` r
devtools::load_all()
#> ℹ Loading excluder
packageVersion("excluder")
#> [1] '0.2.2'
gert::git_log(max = 1)
#> # A tibble: 1 × 6
#>   commit         author          time                files merge message        
#> * <chr>          <chr>           <dttm>              <int> <lgl> <chr>          
#> 1 d99bc23850c3f… Jeffrey R. Ste… 2021-08-08 15:06:45    29 FALSE "Change all te…

devtools::check()
#> ℹ Updating excluder documentation
#> ℹ Loading excluder
#> Warning: [/home/mauro/git/excluder/R/check_duplicates.R:9] @details Link
#> to unavailable package: qualtRics::fetch_survey. there is no package called
#> 'qualtRics'
#> Warning: [/home/mauro/git/excluder/R/check_duration.R:9] @details Link to
#> unavailable package: qualtRics::fetch_survey. there is no package called
#> 'qualtRics'
#> Warning: [/home/mauro/git/excluder/R/check_ip.R:9] @details Link to unavailable
#> package: qualtRics::fetch_survey. there is no package called 'qualtRics'
#> Warning: [/home/mauro/git/excluder/R/check_location.R:9] @details Link to
#> unavailable package: qualtRics::fetch_survey. there is no package called
#> 'qualtRics'
#> Warning: [/home/mauro/git/excluder/R/check_preview.R:9] @details Link to
#> unavailable package: qualtRics::fetch_survey. there is no package called
#> 'qualtRics'
#> Warning: [/home/mauro/git/excluder/R/check_progress.R:9] @details Link to
#> unavailable package: qualtRics::fetch_survey. there is no package called
#> 'qualtRics'
#> Warning: [/home/mauro/git/excluder/R/check_resolution.R:10] @details Link
#> to unavailable package: qualtRics::fetch_survey. there is no package called
#> 'qualtRics'
#> Warning: [/home/mauro/git/excluder/R/qualtrics_numeric.R:3] @description Link
#> to unavailable package: rgeolocate::ip2location. there is no package called
#> 'rgeolocate'
#> Warning: [/home/mauro/git/excluder/R/qualtrics_raw.R:3] @description Link
#> to unavailable package: rgeolocate::ip2location. there is no package called
#> 'rgeolocate'
#> Warning: [/home/mauro/git/excluder/R/qualtrics_text.R:3] @description Link
#> to unavailable package: rgeolocate::ip2location. there is no package called
#> 'rgeolocate'
#> Warning: [/home/mauro/git/excluder/R/remove_label_rows.R:7] @details Link
#> to unavailable package: qualtRics::fetch_survey. there is no package called
#> 'qualtRics'
#> Writing NAMESPACE
#> Writing NAMESPACE
#> ── Building ──────────────────────────────────────────────────────── excluder ──
#> Setting env vars:
#> • CFLAGS    : -Wall -pedantic
#> • CXXFLAGS  : -Wall -pedantic
#> • CXX11FLAGS: -Wall -pedantic
#> ────────────────────────────────────────────────────────────────────────────────
#>      checking for file ‘/home/mauro/git/excluder/DESCRIPTION’ ...  ✓  checking for file ‘/home/mauro/git/excluder/DESCRIPTION’
#>   ─  preparing ‘excluder’:
#>        checking DESCRIPTION meta-information ...  ✓  checking DESCRIPTION meta-information
#>   ─  installing the package to build vignettes
#>      creating vignettes ...  ✓  creating vignettes (2.6s)
#>   ─  checking for LF line-endings in source and make files and shell scripts
#>   ─  checking for empty or unneeded directories
#>   ─  building ‘excluder_0.2.2.tar.gz’
#>      
#> ── Checking ──────────────────────────────────────────────────────── excluder ──
#> Setting env vars:
#> • _R_CHECK_CRAN_INCOMING_USE_ASPELL_: TRUE
#> • _R_CHECK_CRAN_INCOMING_REMOTE_    : FALSE
#> • _R_CHECK_CRAN_INCOMING_           : FALSE
#> • _R_CHECK_FORCE_SUGGESTS_          : FALSE
#> • NOT_CRAN                          : true
#> ── R CMD check ─────────────────────────────────────────────────────────────────
#> * using log directory ‘/tmp/Rtmpcusbks/excluder.Rcheck’
#> * using R version 4.1.0 (2021-05-18)
#> * using platform: x86_64-pc-linux-gnu (64-bit)
#> * using session charset: UTF-8
#> * using options ‘--no-manual --as-cran’
#> * checking for file ‘excluder/DESCRIPTION’ ... OK
#> * this is package ‘excluder’ version ‘0.2.2’
#> * package encoding: UTF-8
#> * checking package namespace information ... OK
#> * checking package dependencies ... OK
#> * checking if this is a source package ... OK
#> * checking if there is a namespace ... OK
#> * checking for executable files ... OK
#> * checking for hidden files and directories ... OK
#> * checking for portable file names ... OK
#> * checking for sufficient/correct file permissions ... OK
#> * checking whether package ‘excluder’ can be installed ... OK
#> * checking installed package size ... OK
#> * checking package directory ... OK
#> * checking for future file timestamps ... OK
#> * checking ‘build’ directory ... OK
#> * checking DESCRIPTION meta-information ... OK
#> * checking top-level files ... NOTE
#> Non-standard files/directories found at top level:
#>   ‘mid-guppy_reprex.R’ ‘mid-guppy_reprex.md’ ‘ok-coqui_reprex.R’
#>   ‘ok-coqui_reprex.spin.R’ ‘ok-coqui_reprex.spin.Rmd’
#> * checking for left-over files ... OK
#> * checking index information ... OK
#> * checking package subdirectories ... OK
#> * checking R files for non-ASCII characters ... OK
#> * checking R files for syntax errors ... OK
#> * checking whether the package can be loaded ... OK
#> * checking whether the package can be loaded with stated dependencies ... OK
#> * checking whether the package can be unloaded cleanly ... OK
#> * checking whether the namespace can be loaded with stated dependencies ... OK
#> * checking whether the namespace can be unloaded cleanly ... OK
#> * checking loading without being on the library search path ... OK
#> * checking dependencies in R code ... OK
#> * checking S3 generic/method consistency ... OK
#> * checking replacement functions ... OK
#> * checking foreign function calls ... OK
#> * checking R code for possible problems ... NOTE
#> collapse_exclusions: no visible binding for global variable
#>   ‘exclusions’
#> Undefined global functions or variables:
#>   exclusions
#> * checking Rd files ... OK
#> * checking Rd metadata ... OK
#> * checking Rd line widths ... OK
#> * checking Rd cross-references ... NOTE
#> Packages unavailable to check Rd xrefs: ‘qualtRics’, ‘rgeolocate’
#> * checking for missing documentation entries ... OK
#> * checking for code/documentation mismatches ... OK
#> * checking Rd \usage sections ... OK
#> * checking Rd contents ... OK
#> * checking for unstated dependencies in examples ... OK
#> * checking contents of ‘data’ directory ... OK
#> * checking data for non-ASCII characters ... OK
#> * checking LazyData ... OK
#> * checking data for ASCII and uncompressed saves ... OK
#> * checking installed files from ‘inst/doc’ ... OK
#> * checking files in ‘vignettes’ ... OK
#> * checking examples ... OK
#> * checking for unstated dependencies in ‘tests’ ... OK
#> * checking tests ...
#>   Running ‘testthat.R’
#>  OK
#> * checking for unstated dependencies in vignettes ... OK
#> * checking package vignettes in ‘inst/doc’ ... OK
#> * checking re-building of vignette outputs ... OK
#> * checking for non-standard things in the check directory ... OK
#> * checking for detritus in the temp directory ... OK
#> * DONE
#> 
#> Status: 3 NOTEs
#> See
#>   ‘/tmp/Rtmpcusbks/excluder.Rcheck/00check.log’
#> for details.
#> ── R CMD check results ───────────────────────────────────── excluder 0.2.2 ────
#> Duration: 56.5s
#> 
#> > checking top-level files ... NOTE
#>   Non-standard files/directories found at top level:
#>     ‘mid-guppy_reprex.R’ ‘mid-guppy_reprex.md’ ‘ok-coqui_reprex.R’
#>     ‘ok-coqui_reprex.spin.R’ ‘ok-coqui_reprex.spin.Rmd’
#> 
#> > checking R code for possible problems ... NOTE
#>   collapse_exclusions: no visible binding for global variable
#>     ‘exclusions’
#>   Undefined global functions or variables:
#>     exclusions
#> 
#> > checking Rd cross-references ... NOTE
#>   Packages unavailable to check Rd xrefs: ‘qualtRics’, ‘rgeolocate’
#> 
#> 0 errors ✓ | 0 warnings ✓ | 3 notes x
```

</details>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.1.0 (2021-05-18)
#>  os       Ubuntu 20.04.2 LTS          
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/Mazatlan            
#>  date     2021-08-10                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  ! package     * version  date       lib source        
#>    AsioHeaders   1.16.1-1 2020-07-07 [1] RSPM (R 4.1.0)
#>    askpass       1.1      2019-01-13 [1] CRAN (R 4.1.0)
#>    assertthat    0.2.1    2019-03-21 [1] CRAN (R 4.1.0)
#>    backports     1.2.1    2020-12-09 [1] CRAN (R 4.1.0)
#>    cachem        1.0.5    2021-05-15 [1] CRAN (R 4.1.0)
#>    callr         3.7.0    2021-04-20 [1] CRAN (R 4.1.0)
#>    cli           3.0.1    2021-07-17 [1] CRAN (R 4.1.0)
#>    commonmark    1.7      2018-12-01 [1] CRAN (R 4.1.0)
#>    crayon        1.4.1    2021-02-08 [1] CRAN (R 4.1.0)
#>    credentials   1.3.1    2021-07-25 [1] RSPM (R 4.1.0)
#>    DBI           1.1.1    2021-01-15 [1] CRAN (R 4.1.0)
#>    desc          1.3.0    2021-03-05 [1] CRAN (R 4.1.0)
#>    devtools      2.4.2    2021-06-07 [1] CRAN (R 4.1.0)
#>    digest        0.6.27   2020-10-24 [1] CRAN (R 4.1.0)
#>    dplyr         1.0.7    2021-06-18 [1] CRAN (R 4.1.0)
#>    ellipsis      0.3.2    2021-04-29 [1] CRAN (R 4.1.0)
#>    evaluate      0.14     2019-05-28 [1] CRAN (R 4.1.0)
#>  P excluder    * 0.2.2    2021-08-07 [?] local         
#>    fansi         0.5.0    2021-05-25 [1] CRAN (R 4.1.0)
#>    fastmap       1.1.0    2021-01-25 [1] CRAN (R 4.1.0)
#>    fs            1.5.0    2020-07-31 [1] RSPM (R 4.1.0)
#>    generics      0.1.0    2020-10-31 [1] CRAN (R 4.1.0)
#>    gert          1.3.1    2021-06-23 [1] CRAN (R 4.1.0)
#>    glue          1.4.2    2020-08-27 [1] CRAN (R 4.1.0)
#>    highr         0.9      2021-04-16 [1] CRAN (R 4.1.0)
#>    hms           1.1.0    2021-05-17 [1] CRAN (R 4.1.0)
#>    htmltools     0.5.1.1  2021-01-22 [1] CRAN (R 4.1.0)
#>    iptools       0.6.1    2018-12-09 [1] RSPM (R 4.1.0)
#>    janitor       2.1.0    2021-01-05 [1] CRAN (R 4.1.0)
#>    knitr         1.33     2021-04-24 [1] CRAN (R 4.1.0)
#>    lifecycle     1.0.0    2021-02-15 [1] CRAN (R 4.1.0)
#>    lubridate     1.7.10   2021-02-26 [1] CRAN (R 4.1.0)
#>    magrittr      2.0.1    2020-11-17 [1] CRAN (R 4.1.0)
#>    maps          3.3.0    2018-04-03 [1] RSPM (R 4.0.3)
#>    memoise       2.0.0    2021-01-26 [1] CRAN (R 4.1.0)
#>    openssl       1.4.4    2021-04-30 [1] CRAN (R 4.1.0)
#>    pillar        1.6.2    2021-07-29 [1] CRAN (R 4.1.0)
#>    pkgbuild      1.2.0    2020-12-15 [1] CRAN (R 4.1.0)
#>    pkgconfig     2.0.3    2019-09-22 [1] CRAN (R 4.1.0)
#>    pkgload       1.2.1    2021-04-06 [1] CRAN (R 4.1.0)
#>    prettyunits   1.1.1    2020-01-24 [1] CRAN (R 4.1.0)
#>    processx      3.5.2    2021-04-30 [1] CRAN (R 4.1.0)
#>    ps            1.6.0    2021-02-28 [1] CRAN (R 4.1.0)
#>    purrr         0.3.4    2020-04-17 [1] CRAN (R 4.1.0)
#>    R6            2.5.0    2020-10-28 [1] CRAN (R 4.1.0)
#>    rcmdcheck     1.3.3    2019-05-07 [1] CRAN (R 4.1.0)
#>    Rcpp          1.0.7    2021-07-07 [1] CRAN (R 4.1.0)
#>    readr         2.0.1    2021-08-10 [1] CRAN (R 4.1.0)
#>    remotes       2.4.0    2021-06-02 [1] CRAN (R 4.1.0)
#>    reprex        2.0.1    2021-08-05 [1] RSPM (R 4.1.0)
#>    rlang         0.4.11   2021-04-30 [1] CRAN (R 4.1.0)
#>    rmarkdown     2.10     2021-08-06 [1] CRAN (R 4.1.0)
#>    roxygen2      7.1.1    2020-06-27 [1] CRAN (R 4.1.0)
#>    rprojroot     2.0.2    2020-11-15 [1] CRAN (R 4.1.0)
#>    rstudioapi    0.13     2020-11-12 [1] CRAN (R 4.1.0)
#>    sessioninfo   1.1.1    2018-11-05 [1] CRAN (R 4.1.0)
#>    snakecase     0.11.0   2019-05-25 [1] CRAN (R 4.1.0)
#>    stringi       1.7.3    2021-07-16 [1] CRAN (R 4.1.0)
#>    stringr       1.4.0    2019-02-10 [1] CRAN (R 4.1.0)
#>    styler        1.5.1    2021-07-13 [1] CRAN (R 4.1.0)
#>    sys           3.4      2020-07-23 [1] CRAN (R 4.1.0)
#>    testthat    * 3.0.4    2021-07-01 [1] CRAN (R 4.1.0)
#>    tibble        3.1.3    2021-07-23 [1] RSPM (R 4.1.0)
#>    tidyr         1.1.3    2021-03-03 [1] CRAN (R 4.1.0)
#>    tidyselect    1.1.1    2021-04-30 [1] CRAN (R 4.1.0)
#>    triebeard     0.3.0    2016-08-04 [1] RSPM (R 4.1.0)
#>    tzdb          0.1.2    2021-07-20 [1] RSPM (R 4.1.0)
#>    usethis       2.0.1    2021-02-10 [1] CRAN (R 4.1.0)
#>    utf8          1.2.2    2021-07-24 [1] RSPM (R 4.1.0)
#>    vctrs         0.3.8    2021-04-29 [1] CRAN (R 4.1.0)
#>    withr         2.4.2    2021-04-18 [1] CRAN (R 4.1.0)
#>    xfun          0.25     2021-08-06 [1] CRAN (R 4.1.0)
#>    xml2          1.3.2    2020-04-23 [1] CRAN (R 4.1.0)
#>    xopen         1.0.0    2018-09-17 [1] CRAN (R 4.1.0)
#>    yaml          2.2.1    2020-02-01 [1] CRAN (R 4.1.0)
#> 
#> [1] /home/mauro/R/x86_64-pc-linux-gnu-library/4.1
#> [2] /usr/local/lib/R/site-library
#> [3] /usr/lib/R/site-library
#> [4] /usr/lib/R/library
#> 
#>  P ── Loaded and on-disk path mismatch.
```

</details>

-

* Inside `if()` I suggest you use `identical()` not `==` because `if()` only takes objects of length 1. `identical()` always returns an object of length 1, but the output of `==` can be longer. If you do use `==` inside `if()` then be sure to first assert the input is indeed of length 1 (e.g. with `stopifnot()`).

* When styling your code I suggest you stick to lines of 80 characters or less. The goal is to be friendly with the reviewers, who may adjust their screen to show the typical 80 characters. Longer lines force them to scroll right, which sounds like a minor issue but after a while can get annoying. The image below shows how the first line of code overflows my 80 characters marker. Under that I have the same code styled in different ways -- all fit in my screen.

<img src=https://i.imgur.com/uGcCKAn.png width=500 />

* In [line 55](https://github.com/JeffreyRStevens/excluder/blob/d99bc23850c3f6f7ae3001cf0b94324b9e0a827b/R/collapse_exclusions.R#L55) I think you need to quote "exclusions". In [`?tidyr::unite()`](https://tidyr.tidyverse.org/reference/unite.html) I see the argument `col` is _The name of the new column, as a string or symbol._ I thinks symbols (e.g. `exclusions`) are allowed for backward compatibility and I believe the tidyverse now recommnds reserving symbols for existing columns and strings (e.g. "exclusions") for new columns. Note the [examples section of `unite()`'s helpflie ](https://tidyr.tidyverse.org/reference/unite.html#examples) uses strings ("z" and "xy") -- not symbols (`z` or `xy`). I tried "exclusions" and successfully removed the NOTE. [Line 60](https://github.com/JeffreyRStevens/excluder/blob/d99bc23850c3f6f7ae3001cf0b94324b9e0a827b/R/collapse_exclusions.R#L60) looks good to me.

Thanks for your work and suggestions for reviewers.

**Comment by JeffreyRStevens** [comment]
Many thanks for the clarifications and help, @maurolepore.
* I believe that I fixed the R CMD note about qualtRics and rgeolocate. I was referencing their documentation, and if you don't have those packages installed, the documentation cannot be linked. So I changed the references to external URLs rather than internal documentation.
* I have now changed all `==` operators to `identical()` in `if()` statements that use user inputted arguments. I have added `stopifnot()` statements when other operators (e.g., `%in%`) are used in `if()` statements with user inputted arguments.
* I greatly reduced the number of lines over 80 characters but did not eliminate them all (e.g., when breaking a line would cause a message to print on two lines or would make readability much worse).
* Thank you for this! The quotes fixed it.

**Comment by maurolepore** [comment]
@ropensci-review-bot add @juliasilge

**Comment by maurolepore** [comment]
@ropensci-review-bot add @jmobrien

**Comment by maurolepore** [comment]
@ropensci-review-bot add @juliasilge to reviewers

**Comment by maurolepore** [comment]
@ropensci-review-bot add @jmobrien to reviewers

**Comment by maurolepore** [comment]
@JeffreyRStevens, I'm thrilled that @juliasilge and @jmobrien accepted to review the excluder package. 

Note `@ropensci-review-bot` set the due date following rOpenSci's guidelines to 2021-09-20. However, these are difficult times and I would like to allow reviewers 1 extra week. Feel free to submit your review whenever ready but if you don't I'll touch base on 2021-09-27.

I look forward to working with you all.

**Comment by juliasilge** [comment]
## Package Review

Congratulations to the author on this useful package for folks handling Qualtrics surveys. It will be convenient to have all these common checks in a consistent set of functions, and the messaging in the console is very nice. 🙌 

- [x] As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (If you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [x] **A statement of need** clearly stating problems the software is designed to solve and its target audience in README
- [x] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [x] **Vignette(s)** demonstrating major functionality that runs successfully locally
- [x] **Function Documentation:** for all exported functions
- [x] **Examples** (that run successfully locally) for all exported functions
- [x] **Community guidelines** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

On documentation, I find some of the way the documentation works a bit confusing, especially when things go wrong for users. For example, if I have a dataset with no IP addresses or location information and I try to run `exclude_duplicates()`, I get this error:

```
Error in check_duplicates(x, quiet = TRUE, ...) : 
The column specifying location ('location_col') was not found.
```

However, when I look at the documentation for the function I used, I don't see anything about `location_col` and it's not clear which link I should click to find the relevant info. Some options might be to change the documentation for the dots or write a more clear error message.


#### Functionality

- [x] **Installation:** Installation succeeds as documented.
- [x] **Functionality:** Any functional claims of the software been confirmed.
- [x] **Performance:** Any performance claims of the software been confirmed.
- [x] **Automated tests:** Unit tests cover essential functions of the package
   and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [x] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines

Estimated hours spent reviewing: 2

- [x] Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

---

### Review Comments

🎯 The function name `collapse_exclusions()` reminds me a bit too much of `dplyr::collapse()` when what it does is much more like `tidyr::unite()`. What about a name like `unite_exclusions()`? Along those lines, did you consider names like `filter_*()` instead of `exclude_*()`? A benefit to using names that align with other names in the ecosystem is that these functions then slot right in to people's mental model of what they are doing.

🎯 None of my real surveys have IP addresses so I was not able to check the iptools integration beyond the example survey data included in the package.

🎯 In the future, if you wanted to increase the polish of the console messages (once the nicest features of this package that I think will draw folks to use it), you might check out using [cli](https://cli.r-lib.org/).

**Comment by maurolepore** [comment]
@juliasilge thanks for your review. 
 @jmobrien when do you think you'll be able to submit yours?

**Comment by jmobrien** [comment]
I will have it in by later today, thanks.

**Comment by jmobrien** [comment]
## Package Review

*Please check off boxes as applicable, and elaborate in comments below.  Your review is not limited to these topics, as described in the reviewer guide*

- **Briefly describe any working relationship you have (had) with the package authors.**
- [X] As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (if you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [X] **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README
- [X] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [X] **Vignette(s):** demonstrating major functionality that runs successfully locally
- [X] **Function Documentation:** for all exported functions (**but see below**)
    
- [X] **Examples:** (that run successfully locally) for all exported functions
- [X] **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

#### Functionality

- [X] **Installation:** Installation succeeds as documented.
- [X] **Functionality:** Any functional claims of the software been confirmed.
- [X] **Performance:** Any performance claims of the software been confirmed.
- [X] **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [X] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines (**but see below**).

Estimated hours spent reviewing: 7

- [X] Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

---

### Review Comments

#### Overall
I quite like this package.  It fills a niche for Qualtrics data cleaning that is difficult to automate and/or make auditable/reproducible, given how Qualtrics designed server-side data filters.  

As the author notes, in human participants research it's also important to not unduly exclude data, and the manual review this helps facilitate is supportive of that ethical imperative.  So, generally, I think, the paradigm of `excluder` makes a lot of sense--a simple interface for early-stage review and removal of problem cases.  

The package seemed to work as expected.  None of the data I had available (apparently) had any non-US participants, so I also was not able to test IP-checking as thoroughly as might be warranted, but it seems like a sound implementation.

#### A few notes

A few things that might warrant either review or improvement. Nothing terribly serious or strictly essential for fixing right now--though with one issue (centering everything around the `check_*()` functions), I do wonder  that it might make growing/maintaining this package harder in the long run.

* Style & dependencies
  *  seem to be a bit inconsistent
  * mostly choices to use tidyverse vs. base functions, e.g.:  
    * `dplyr::bind_cols()` is mixed with `rbind()`.  
    * `dplyr::pull()` is regularly used for indexing that could be handled by `[[]]`.  
  * Nothing seems strictly wrong, but the motivation for each choice wasn't always clear


* some function calls reference function re-exports rather than the originals 
  * e.g., `dplyr::all_of()` instead of `tidyselect::all_of()`.
  * Not currently clear which approach is preferable, but thought it worth mentioning.
  
  
* Interaction b/w `check`, `mark`, and `exclude` verbs internally & in workflow:
  * Again, I like the verbs as an overarching approach.
  * However, considering [Mozilla guidelines](https://mozillascience.github.io/codeReview/review.html) on simplicity/efficiency, I do wonder about everything depending on the `check_*()` functions
  * Outlining here:
    * `mark_*()` functions pass everything to `check_*()`, 
    extracts a specified ID variable from that, adds a marker text variable,
    then merges this back with `left_join()`
    * `exclude_*()` functions pass everything to `check_*()`
    then uses `anti_join()` on just the ID variable
  * I think this arrangement might unnecessarily complicate some tasks.  For example:
    * Output from `mark_*()` functions end up with `NA` in non-marked rows of `exclusion_` variables. This  makes manual filtering on these columns more difficult.
    * `mark_duration()` can't easily mark the difference b/w a too-short and a 
    too-long response, which might be a useful thing to know. 
    * `mark_*()` and `exclude_*()` use ellipses for
    arguments to be passed to `check_*()`, meaning you have to look up 
    `check_*()` to get comprehensive help on how `mark_*()` and `exclude_*()` 
    operate (this specific issue could probably be fixed with a few explicit 
    arguments in each function, even if everything else is left the same)
  *  [*personal opinion here*]-- could it be simpler & more useful if 
  package functionality built on the `mark_*()` functions, rather than `check_*()`?
      * `mark_*()` functions could cover all reporting.  This could even enable some 
    time-saving advantages from `summarize()`-like reporting, (e.g., could see at a 
    glance if all short-duration cases were those also out-of-US).  
      * `exclusion_*` variables from `mark` could use booleans, 1/0, (or even just ""), 
    for easier support of manual filtering if desired
      * `check_*()` and `exclude_*()` could be simplified:
          * Under the current design (3 functions for each characteristic),
      `check` and `exclude` could just call `mark` internally plus something 
      like `dplyr::filter()`.
          * Potentially, `check` and `exclude` could even be reduced to just 2 
      general-purpose that keep/exclude based on any added `exclusion_` variables 
      * Efficiency might be improved by avoiding duplicating passes on the data--
    maybe not noticeable enough to matter for smaller use cases
    (such as those more typical for we psychologists), potentially useful for 
    potential users who work regularly with larger-scale datasets.

* Few small other things:
  * use of & instead of && in if statements that should only field one comparison
  * descriptions of `check_ip()`, `exclude_ip()`, and `mark_ip()` are backwards--each
  retains/drops cases from **outside** the specified country, not from **inside** it as indicated in the documentation
  * the rOpenSci packaging guidelines recommends an `[object]_[verb]` structure,
  while this uses the reverse.  Personally, I think current naming is fine, though.
  * Packaging guidelines generally recommend not having a separate file for each function, but having at least a bit of conceptual organization.  The names help here, but it did slow down my navigating the package.

**Comment by maurolepore** [comment]
@jmobrien thanks a lot for your review.

@JeffreyRStevens, you can now go ahead and address reviewer's comments. rOpenSci's guidelines seem to not limit how long you should take, but I think it's best to respond ASAP -- while the reviewers keep the context in their heads. 

Please let me know if you have questions.

**Comment by JeffreyRStevens** [comment]
Yes, many thanks @juliasilge and @jmobrien for your helpful reviews! I've done a quick skim and will review in-depth very soon. I may have a few questions before I get too far into revisions.

**Comment by JeffreyRStevens** [comment]
@juliasilge, many thanks again for your helpful comments. Here are some responses/questions for your points:
* Confusing error/documentation for `exclude_duplicates()`: I think I see the issue here, and I believe that addressing some of @jmobrien's concerns about the functions will address this. I'll return to this comment after I address his concerns.
* Rename `collapse_exclusions()`: This was a great idea. I have now renamed this to `unite_exclusions()` and marked `collapse_exclusions()` as deprecated using the `{lifecycle}` package. I will push this change after I resolve the next concern.
* Rename `exclude_*()` functions to `filter_*()`: I really like this idea, too. But one question that I had is whether I should rather use `filter_*()` to replace the `check_*()` functions since the tidyverse `filter()` function *retains* the specific rows rather than *removes* them. In this sense, it seems to be more equivalent to `check_*()` rather than `exclude_*()`, in that `check_*()` retains the rows of data that are being checked. Or maybe I'm thinking of it backwards. What are your thoughts on this?
* Thank you so much for pointing me to `{cli}`. I hadn't seen that before, and it looks like a very useful package for customizing messages. I'll definitely be figuring out ways to integrate that into the console messages.

I'll have some questions for @jmobrien in the coming days.

**Comment by juliasilge** [comment]
I was really happy to see @jmobrien's thorough review and I agree that working through some of his suggestions will address the problems with the documentation and error messages.

I'm not sure what we really mean by a difference between "retain" vs. "throw away" (just reverse the condition, which in the case of, say, IP addresses in/out of the US doesn't seem like a super one-way thing) but I think I see your point. I guess my opinion is that creating three new verbs for operations that are arguably the same as things many people already use makes this toolkit less easy to use than if they were given names that allude to the ways in which they are the same as other operations. Another option may be to use `mark_` + `filter_` + `exclude_`?

**Comment by jmobrien** [comment]
I also will say that I generally agreed with all that @juliasilge said in her review and thought it was on point.  Where I didn't echo her sentiments directly, it was mostly for brevity because I was the second to submit and my review was already verbose.  I especially agree that the console reporting is a big sell here. 

Here, @JeffreyRStevens, I'm understanding you as saying `exclude_duration([longer than 30 mins])` would remove all >30 minute cases, while `filter([duration > 30 mins])` would keep those same cases and discard others.  So, at least at default, the behavior of `filter` is more conceptually similar to `check` than `exclude`.  That right?  If so, I see where you're coming from also.  

From a more data-centric perspective on the potential userbase, I agree w/where Julia's coming from.  The package does things very close to core tidyverse operations for data wrangling. There's something to be said for capitalizing on what those names invoke. 

With my social scientist had on, though, I feel much more positively about the existing names.  This whole package really just seems like a batch of convenience functions that abstract lower-level data wrangling operations into key *tasks* for ethically managing human-participants data.  As tasks, I think the names make sense: manually "check" problems first, then "exclude" them prior to analysis.

I don't have a strong opinion about which way naming should go.  Though FWIW, I suppose similar ideas are embedded in my speculation whether functionality should center on `mark`.  With that workflow, the `check` and `exclude` verbs could keep their core purpose as convenience functions called downstream of `mark` (give me all the marked stuff for review vs. get rid of it).  But if you find yourself needing something more complex, you can just do a standard call to `filter` instead.

(Or, if you're feeling really ambitious, maybe you could make everyone happy by adding something like `filter_exclusions()` that could emulate the typical filter syntax for more complex cases where the convenience functions fall short?  So, e.g., `filter_exclusions(!ip, duration)` could mean "give me all the cases that were NOT marked as out of the acceptable IP address space, but which were still too long", etc.  Could maybe also work around whether `unite_exclusions()` has been called yet or not.)

**Comment by juliasilge** [comment]
I don't know that I'd recommend adding another set of functions to maintain here. And for the record, my opinion on the naming is not super strong either; I'm raising this mostly because this is something I've run into before and in the past I have always regretted when I have not used what already exists in terms of vocabulary, norms, idioms, function names, etc. and then later realized I could have.

**Comment by JeffreyRStevens** [comment]
Thanks you two for your thoughts on this. Yes, my thought was that `filter_`, `mark_`, and `exclude_` would more closely match the way `filter()` works (that is, it retains rows satisfying the condition). But I also share @jmobrien's point that `check_` might make more sense from a general user perspective even though `filter_` makes sense from a tidyverse user/developer perspective. I'll grapple with this in the coming days.
I really like the idea of centering the functions around `mark_` rather than `check_`. @jmobrien, just to clarify, you were also suggesting removing all of the `check_` and `exclude_` functions and instead only have two functions: `check` and `exclude`, correct? So basically, you would always run the `mark_` functions to find the exclusions, then pipe that to `check` to view/store the exclusions or pipe to `exclude` to remove the exclusions. Is this what you were suggesting? This sounds much easier to maintain and probably to use as well.

**Comment by jmobrien** [comment]
That was one option, yes.  I guess in that simplifying approach `check` and `exclude` would need to recognize what parts that `mark` functions had looked at previously.  You could set that up a number of different ways.  

You could also preserve the existing `check`/`exclude` function sets if you prefer a more standalone design where each verb can operate on fresh data directly.  Even then, as outlined above I think there are several benefits to having `check` and `exclude` call `mark` internally, rather than `mark` and `exclude` calling `check`.  

There's certainly some draw to option 1.  But both options have unique advantages, and I don't want to dictate your design choices.  

Option 1's a more major change, though, so if you're leaning that way I might get others' opinions first.

**Comment by JeffreyRStevens** [comment]
I'm close to finishing up revisions. I have a couple more changes to make and had two questions for @jmobrien. 
1. When you referred to avoiding multiple passes on the data, did you mean within a function or are you concerned about running multiple `mark_*()` functions?
2. When you referred to using ellipses to pass arguments to (now) `check_*()` and `exclude+*()` functions, you suggested explicitly including some arguments. Can you point me to how to do this? My efforts to do this have not worked out.

**Comment by JeffreyRStevens** [comment]
OK, I think that I have addressed all of the concerns. Please let me know if I missed something or you have additional questions. Note that I have increased the version to 0.3.0 since I have made major changes to the code and deprecated a function.

## Responses to @juliasilge.
* Confusing error/documentation for `exclude_duplicates()`: This has been addressed by explicitly including arguments from `mark_*()`. [Commit 1b74c4ce](https://github.com/JeffreyRStevens/excluder/commit/1b74c4ce1d982d2af816cdc2b37bbdf6538887b8)
* Rename `collapse_exclusions()`: This was a great idea. I have now renamed this to `unite_exclusions()` and marked `collapse_exclusions()` as deprecated using the `{lifecycle}` package. [Commit 68aae92b](https://github.com/JeffreyRStevens/excluder/commit/68aae92beade3b14d8018fd55f205f42e8389c2e#diff-8c2574892063f995fdf756bce07f46c1a5193e54cd52837ed91e32008ccf41ac).
* Rename `exclude_*()` functions to `filter_*()`: I'm still torn on this, but I think that I will keep the names as originally named. In part, this is due to the confusion that we've had about whether `check` or `exclude` should be changed to `filter`. I now use filter for both types of actions. Maybe a compromise is to use the word 'filter' more in the documentation?
* Thank you so much for pointing me to `{cli}`. I hadn't seen that before, and it looks like a very useful package for customizing messages. I'll definitely be figuring out ways to integrate that into the console messages.

## Responses to @jmobrien
* Using both `dplyr::bind_cols()` and `rbind()`: I have switched all `rbind()` uses to `dplyr::bind_cols`. [Commit 89294932](https://github.com/JeffreyRStevens/excluder/commit/89294932e1c4412cc986c1b69dc359484af9b600)
* Using `dplyr::pull()` instead of `[[]]`: I have switched all `dplyr::pull()` uses to `[[]]`. [Commit ec655f9b](https://github.com/JeffreyRStevens/excluder/commit/ec655f9bdbe7d8a73655999d4a204e53a7016b40)
* Referencing function re-exports instead of original package: I have changed all references to `dplyr::all_of()` and `dplyr::any_of()` to `tidyselect::all_of()` and `tidyselect::any_of()`. Are there ways to easily find the original package for all of your functions in a script? [Commit face90d](https://github.com/JeffreyRStevens/excluder/commit/face90d864784f92fcd633af884e77339e2fb8e3)
* Move primary functionality from `check_*()` to `mark_*()` functions: I have now done this. The `check_*()` and `exclude_*()` functions now just run the `mark_*()` functions and filter exclusions in or out. [Commit 877e3b9](https://github.com/JeffreyRStevens/excluder/commit/877e3b9b33d12147950545516c29e9d1fef3e43d)
* Mark functions result in NAs when no exclusions apply: The NAs have now been replaced with "". [Commit 877e3b9](https://github.com/JeffreyRStevens/excluder/commit/877e3b9b33d12147950545516c29e9d1fef3e43d)
* `mark_duration()` does not differentiate between too long and too short: `mark_duration()` now marks quick and slow durations separately. [Commit d45e44a6](https://github.com/JeffreyRStevens/excluder/commit/d45e44a630bef06651798d09adc53710525fcd6b)
* `mark_*()` and `exclude_*()` use ellipses for arguments to be passed to `check_*()`: This has been addressed by explicitly including arguments from `mark_*()`. [Commit 1b74c4ce](https://github.com/JeffreyRStevens/excluder/commit/1b74c4ce1d982d2af816cdc2b37bbdf6538887b8)
* Create two general-purpose functions `check` and `exclude`: I've decided to hold off on this for the moment. Instead, I have offered an example in the vignette on piping multiple `mark_*()` functions and then check with a filter. [Commit 12b4ad2b](https://github.com/JeffreyRStevens/excluder/commit/12b4ad2b9622184bccc747d5999696ced8e2dc8d)
* Avoid duplicate passes on data: This may be an optimization issue to deal with later.
* Use `&&` instead of `&`: I have now replaced `&` with `&&`. [Commit b9aa1b04](https://github.com/JeffreyRStevens/excluder/commit/b9aa1b04ff09a0bc0931f7bf13797104fb76e7a7)
* The ip functions were inaccurately described in documentation: I have fixed the documentation to clarify that these functions find cases *outside* of the specified country. [Commit 3b486a20](https://github.com/JeffreyRStevens/excluder/commit/3b486a2085382898685388094ffa1ec2b617561e)
* Reverse order of function names to `[object]_[verb]`: While I saw that this was a preference for rOpenSci packages, it does not seem natural for this set of functions. `[verb]_[object]` both categorizes the verbs better and matches {tidyverse} syntax (e.g., `bind_rows()`/`bind_cols()`) as well as the {qualtRics} syntax (e.g., `fetch_survey()`).
* Organize related functions into files: I have now organized the functions by the exclusion type (e.g., `duplicates.R`). [Commit 3c88d484](https://github.com/JeffreyRStevens/excluder/commit/3c88d484d75ca9a2ebb9b3bafac699a74fed06ab)

**Comment by maurolepore** [comment]
Thanks everyone! It's been great to watch this review. 

Dear reviewers @juliasilge and @jmobrien,

> At this stage, we ask that you respond as to whether the changes sufficiently address any issues raised in your review. We encourage ongoing discussion between package authors and reviewers, and you may ask editors to clarify issues in the review thread as well.
> -- https://devguide.ropensci.org/reviewerguide.html#followupreviewer

**Comment by JeffreyRStevens** [comment]
@maurolepore, what are the next steps now? FYI, I'm working on a paper for JOSS. I'm not sure if that should be part of the review here or just over at JOSS.

**Comment by maurolepore** [comment]
@JeffreyRStevens, 

I'm watching your discussion with the reviewers. Do you feel the ball is no longer on your court? If so I would ask the reviewers once again whether your changes sufficiently address any issues they raised in the review. Please confirm and I'll write a new comment with a `@mention` to them.

We no longer review submissions to JOSS, but do mention the review -- I think you might get fast-tracking.

**Comment by JeffreyRStevens** [comment]
@maurolepore, yes, I think that I've addressed the reviewers concerns, and I'm waiting for their final approval. Thanks.

**Comment by maurolepore** [comment]
Dear reviewers,

@jmobrien, do you have an estimate about when you might be able to confirm whether the changes made are sufficient to approve this package?

@juliasilge, it seems your last concern (return visibly) has been addressed. Is there anything else you'd like to request or do you confirm the changes made are sufficient to approve this package?

**Comment by jmobrien** [comment]
Mauro, and Jeffrey, apologies--I've had a remarkable variety of unexpected
home and family issues come up over just this past week.  I'm about to go
handle what I hope is the last of them, but I'll make it a priority to
finish everything tomorrow.  Thanks for your patience.

**Comment by juliasilge** [comment]
For me, the changes have addressed the issues I was interested in, and I approve it moving forward. ✅

**Comment by jmobrien** [comment]
This looks much better.  The modularization achieves a lot of the code streamlining I was hoping for, especially.  

I think I'm ready to approve, except for one maybe-bug and maybe 1 or 2 suggestions:

**1. Small bug(?):**

`mark_ip()` checks for missing IPs (previews, mostly) and notes them, but doesn't actually mark those rows.  Thus, they aren't kept in `check_ip()` and they're left in with `exclude_ip()`.  If this is intentional (because `mark_preview()` exists), then fine, but otherwise this should be fixed.

**2. marking columns in `check_*()` functions**

Currently `check_()` functions drop the marking variable columns. But since `check_()*` seems intended for manual review, and the marks sometimes have useful summary notes (e.g., duration).  Would it make sense to keep them in, or at least have an argument for that?  If so, I also might move them to the first column in that case for easier viewing if a survey is long.

3. Exclusions for `exclude_*()`?

Is the philosophy for having `check_*()` functions that, following review, you might sometimes see cases you still want to keep?  If so and that occurs, it seems like `exclude_*()` stops working well.  There's no way to note which cases you want to protect (other than modifying the actual data, which presumably you don't want to do).   

I'm not sure how you would want to approach an explicit feature for this, so I don't think adding one should hold up approval. Maybe something to consider for the future.  Still, if this does fit the intended use for `check_*()`, maybe a simple addition to the vignette covering how to do this with a `mark` --> [adjustments] --> `filter` workflow in lieu of `exclude` would be good for users to see.


I think all of the above should be pretty trivial to implement, and ignore them if they don't fit your goals.  Other than that, I think this is ready to go!  Great work!

**Comment by JeffreyRStevens** [comment]
@jmobrien, @juliasilge, @maurolepore, I have a question for you all.
I'm working on the issues raised above and have created a new function (in `utils.R`) called `keep_marked_column()` that is used in the `check_*()` functions. This function reads in the data, the name of the exclusion column that is created by the `mark_*()` function, and a flag for whether to keep the column in the output (as per item 2 above). It then simply removes or relocates the exclusion column based on the flag. However, I'm running into a problem with passing R CMD checks. 
When I run the R CMD check on the package with the function as it is currently written (and pushed), I receive the dreaded `no visible binding for global variable` note. This seems to result from when I embrace the column name with `{{ }}` in line 31: `x %>% dplyr::select(-{{ column }})`. If I switch to an indirect call of the column name with `.data[[column]]` (as used in line 33), I receive an error that the column name is not found (e.g., when running `check_duplicates()`, I get `Error: object 'exclusion_duplicates' not found`). I can get it to work with `.data[[!!rlang::enquo(column)]]`, but then I get the check error again.
Is there a more elegant way of resolving this besides assigning all of the columns to a `globalVariables()` call?

**Comment by maurolepore** [comment]
@JeffreyRStevens, I'm willing to help. Can you share the link to a branch or PR so I can pull it locally and reproduce the issue?

**Comment by JeffreyRStevens** [comment]
@maurolepore, many thanks! It is just on the main branch at https://github.com/JeffreyRStevens/excluder.

**Comment by jmobrien** [comment]
@JeffreyRStevens took a glance at it on your page.  Just a thought, but I'm actually wondering if simplest solution to what you're facing may be to just make the `column` argument of `keep_marked_column()` take a string instead of a bare name.  Then, just use `all_of()` inside each of the `select` and `relocate` functions?

The name being passed into `keep_marked_column()` is known and fixed for each `check` function, so I don't think you need anything more flexible.  And the name itself is really all you'll ever need out of that argument, so a string seems like it could be fully adequate?

(You could also do something similar using `deparse(substitute(column))`, or some more "tidy" equivalent, inside the function)

**Comment by jmobrien** [comment]
Working with the current approach, might this work?

I haven't tested it in a build and @JeffreyRStevens might know something better/more best-practices, but I think it's an option.

```r
keep_marked_column <- function(x, column, keep) {
  col <- rlang::ensym(column)
  if (identical(keep, FALSE)) {
    x %>% dplyr::select(!!col)
  } else {
    x %>% dplyr::relocate(!!col)
  }
}
````

**Comment by maurolepore** [comment]
@JeffreyRStevens,

My local experiment suggests that adding `.data$` to your column names avoids the R CMD check NOTE. To confirm the checks on GitHub Actions I believe you'll need to approve the workflows somehow (apparently because I'm a first-time contributor to your package).

<img src=https://i.imgur.com/TRiWY1P.png width=500>

https://github.com/JeffreyRStevens/excluder/pull/5/files

My suggestion is independent to the advice that @jmobrien shared.

--

Also, while I'm here, you may simplify the `if()` clause:

``` r
keep <- FALSE
out <- "it's true"
if (!keep) {
  out <- "it's false"
} 
out
#> [1] "it's false"

keep <- TRUE
out <- "it's true"
if (!keep) {
  out <- "it's false"
} 
out
#> [1] "it's true"
```


See https://speakerdeck.com/jennybc/code-smells-and-feels?slide=44

**Comment by JeffreyRStevens** [comment]
@jmobrien 
1. Small bug(?):
I have now added a flag in `mark_ip()` that tracks whether to include NAs.

2. marking columns in check_*() functions
I have now added a flag in the `check*_()` functions that tracks whether to keep (and move to the first column) the exclusion column or remove it.

3. Exclusions for exclude_*()?
This is an interesting idea that I would like to think about a bit before doing anything. If you're OK with it @jmobrien, I'd like to wait to deal with this until after approval.

Is there anything else?

**Comment by JeffreyRStevens** [comment]
I have increased testing coverage with some additional tests. @jmobrien, does this meet your final approval?

**Comment by maurolepore** [comment]
> I think all of the above should be pretty trivial to implement, and ignore them if they don't fit your goals. Other than that, I think this is ready to go! Great work!
-- https://github.com/ropensci/software-review/issues/455#issuecomment-956550189

The way I interpret @jmobrien's comment is that he didn't need another round of review. You have addressed all his latest comments, so congratulations @JeffreyRStevens -- excluder is approved!

And once again thanks @juliasilge and @jmobrien for your amazing work!

I'll follow up soon with some more comments and instructions.

**Comment by maurolepore** [comment]
@ropensci-review-bot approve excluder

**Comment by maurolepore** [comment]
@ropensci-review-bot approve excluder

**Comment by maurolepore** [comment]
@JeffreyRStevens I think the comment above includes everything you except two things:


1. As you intend to submit to CRAN, please see https://devdevguide.netlify.app/building.html#crangotchas

2. See the links under [Package promotion](https://devdevguide.netlify.app/editorguide.html#package-promotion).

**Comment by JeffreyRStevens** [comment]
This is fantastic news! Many thanks @maurolepore, @juliasilge, and @jmobrien for the time and effort you have put into reviewing this package. It is soooo much better after your review, and I have learned a ton.

**Comment by JeffreyRStevens** [comment]
@maurolepore, I believe I have fully transitioned the package over to rOpenSci. The one remaining issue that I can't sort out is how to change the URL link in the About section of the GitHub page (https://github.com/ropensci/excluder) to https://docs.ropensci.org/excluder/. It is currently still linking to jeffreyrstevens.github.io/excluder even though I have changed all of the links in the repo. Do you know how to change this or will it just resolve on its own at some point?

**Comment by maelle** [comment]
@JeffreyRStevens I've made you admin of your repo again, so you should be able to make changes now.

Admin rights are always lost during transfer, but we're working on a bot command for allowing package authors themselves to reclaim them. You'll experience a smoother experience if you submit a second package. :wink:

**Comment by jmobrien** [comment]
Sorry @JeffreyRStevens  and @maurolepore, my internet was out almost all of yesterday and I was dealing with that. But @maurolepore was correct about my stance.  Just so it's explicit: I'm happy about the changes and am glad to see this approved!  Congrats!

**Comment by JeffreyRStevens** [comment]
Many thanks @maelle and @maurolepore. I have now changed the URL.
And thanks, @jmobrien!
