### ISSUE TITLE
ILSM: Analyze Interconnection Structure of Multilayer Interaction Networks

### ISSUE THREAD

**Issue by WeichengSun** [ropensci/software-review#661]
Submitting Author Name: Weicheng Sun
Submitting Author Github Handle: @WeichengSun
Other Package Authors Github handles: (comma separated, delete if none) 
Repository:  https://github.com/WeichengSun/ILSM
Version submitted: 1.0.3.2
Submission type: Standard
Editor:  TBD 
Reviewers:  TBD 

Archive: TBD
Version accepted: TBD
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: ILSM
Title: Analyze Interconnection Structure of Multilayer Interaction Networks
Version: 1.0.3.2
Authors@R: c(
    person("Weicheng", "Sun", , "sunwch2023@lzu.edu.cn", role = c("aut", "cre")),
    person("Chuan", "Yan", , "yanchuan@lzu.edu.cn", role = c("aut")),
    person("Yangyang", "Zhao", , "120220907711@lzu.edu.cn", role = c("aut")))
Description: 
    In view of the analysis of the structural characteristics of the multilayer 
    network has been complete, however, there is still a lack of a unified 
    operation that can quickly obtain the corresponding characteristics of the 
    multilayer network. 
    To solve this insufficiency, 'ILSM' was designed for supporting calculating 
    such metrics of multilayer networks by functions of this R package.
License: MIT + file LICENSE
URL: https://github.com/WeichengSun/ILSM
BugReports: https://github.com/WeichengSun/ILSM/issues
Encoding: UTF-8
Roxygen: list (markdown = TRUE, roclets = c ("namespace", "rd", "srr::srr_stats_roclet"))
RoxygenNote: 7.3.1
Depends: R (>= 3.5.0)
Imports: 
    stats,
    Matrix,
    igraph
Suggests: 
    knitr,
    rmarkdown,
    testthat (>= 3.0.0)
VignetteBuilder: knitr
Config/testthat/edition: 3

```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] data extraction
	- [x] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [x] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):
 
This package that wrap professional programs used for multilayer interaction network research. These programs must be specific to interconnection structure.  It focuses on interacnnection motif for handling matrices or 'igraph'data.

-   Who is the target audience and what are scientific applications of this package?
 
In community ecology, ecological network is used to represent the complex ecological interaction system. Therefore, researchers in this field often pay attention to the work from the network perspective. Therefore, this package is based on the multilayer ecological network to study the interconnection structure, hoping to provide convenience for the mentioned audience.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
 
There is an R package(bmotif) that does similar work in the field of ecological networks, but the program provided by it is only used to study the structure of bipartite networks and is relatively simple, while the new package only studies the structure of multilayer interacting networks, which is more complex.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

n/a

-   If you made a pre-submission inquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

[#654](https://github.com/ropensci/software-review/issues/654)

-   Explain reasons for any [`pkgcheck` items](https://docs.ropensci.org/pkgcheck/) which your package is unable to pass.

Because we have submitted the package ILSM to CRAN ahead of time, the package name is duplicated and the  [`pkgcheck` items](https://github.com/WeichengSun/ILSM/actions/runs/11073028649) result is not available.

## Technical checks

Confirm each of the following by checking the box.

- [x] I have read the [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).
- [x] I have read the [author guide](https://devdevguide.netlify.app/authors-guide.html) and I expect to maintain this package for at least 2 years or to find a replacement.

This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage.

## Publication options

- [ ] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [x] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [x] The package is novel and will be of interest to the broad readership of the journal.
- [x] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.org/code-of-conduct/) during the review process and in maintaining my package should it be accepted.

**Comment by WeichengSun** [comment]
Hi @adamhsparks, I can't fix this check error: ✖️ Package name is not available (on CRAN).
Because the ILSM on CRAN and this submission here are all my projects

**Comment by adamhsparks** [comment]
yes, I'm aware, I checked your README and CRAN. Thanks for clarifying though!

**Comment by adamhsparks** [comment]
Hi @WeichengSun, there's a few NOTEs that I've found when I run checks locally, could you please work to address them as I find a handling editor for {ILSM}?

```r
❯ checking top-level files ... NOTE
  Non-standard files/directories found at top level:
    ‘Contributing.Rmd’ ‘README.Rmd’ ‘codemeta.json’

❯ checking Rd files ... [0s/0s] NOTE
  checkRd: (-3) coid.Rd:32: Lost braces
      32 | \itemize{\item{\code{network.or.subnet_mat1}: input a 'igraph' of network data independently or input sparse matrix together with \code{subnet_mat2}.}}
         |               ^
  checkRd: (-3) coid.Rd:35: Lost braces
      35 | \itemize{\item{\code{network.or.subnet_mat1}: must input matrix(or data.frame) together with \code{subnet_mat2}. the matrix can be sparse matrix and matrix of interaction strength.}}
         |               ^
  checkRd: (-3) coid.Rd:41: Lost braces
      41 | \item{(1). Input in a network of type "igraph" alone.}
         |      ^
  checkRd: (-3) coid.Rd:42: Lost braces
      42 | \item{(2). Must be entered as data frame or matrix with \code{subnet_mat2}.}
         |      ^
  checkRd: (-3) coid.Rd:47: Lost braces
      47 | \item{Try to make the rows of both matrices have the same attributes. Or we default:}
         |      ^
  checkRd: (-3) coid.Rd:49: Lost braces
      49 | \item{When the two matrices can have different numbers of rows:}
         |      ^
  checkRd: (-3) coid.Rd:51: Lost braces
      51 | \item{(1). If both matrices have row names, then the function counts all row names to produce two new matrices with the same row names.}
         |      ^
  checkRd: (-3) coid.Rd:52: Lost braces
      52 | \item{(2). If at most one matrix has row names, the function assigns new row names to both matrices on a row-to-row basis (any extra row names are assigned a new value) and then counts all row names to produce two new matrices with the same row names.}
         |      ^
  checkRd: (-3) coid.Rd:55: Lost braces
      55 | \item{When the two matrices can have the same numbers of rows:}
         |      ^
  checkRd: (-3) coid.Rd:57: Lost braces
      57 | \item{No matter how the row names of the two matrices are arranged, as long as the row names are exactly the same; But we don't handle matrices with empty row names (the function will give an error).}
         |      ^
  checkRd: (-3) coid.Rd:60: Lost braces
      60 | \item{The two matrices can have different numbers of rows, but read our default handling carefully to make sure the calculation is accurate when using this function!!!}
         |      ^
  checkRd: (-3) cois.Rd:32: Lost braces
      32 | \itemize{\item{\code{network.or.subnet_mat1}: input a 'igraph' of network data independently or input sparse matrix together with \code{subnet_mat2}.}}
         |               ^
  checkRd: (-3) cois.Rd:35: Lost braces
      35 | \itemize{\item{\code{network.or.subnet_mat1}: must input matrix(or data.frame) together with \code{subnet_mat2}. the matrix can be sparse matrix and matrix of interaction strength.}}
         |               ^
  checkRd: (-3) cois.Rd:41: Lost braces
      41 | \item{(1). Input in a network of type "igraph" alone.}
         |      ^
  checkRd: (-3) cois.Rd:42: Lost braces
      42 | \item{(2). Must be entered as data frame or matrix with \code{subnet_mat2}.}
         |      ^
  checkRd: (-3) cois.Rd:47: Lost braces
      47 | \item{Try to make the rows of both matrices have the same attributes. Or we default:}
         |      ^
  checkRd: (-3) cois.Rd:49: Lost braces
      49 | \item{When the two matrices can have different numbers of rows:}
         |      ^
  checkRd: (-3) cois.Rd:51: Lost braces
      51 | \item{(1). If both matrices have row names, then the function counts all row names to produce two new matrices with the same row names.}
         |      ^
  checkRd: (-3) cois.Rd:52: Lost braces
      52 | \item{(2). If at most one matrix has row names, the function assigns new row names to both matrices on a row-to-row basis (any extra row names are assigned a new value) and then counts all row names to produce two new matrices with the same row names.}
         |      ^
  checkRd: (-3) cois.Rd:55: Lost braces
      55 | \item{When the two matrices can have the same numbers of rows:}
         |      ^
  checkRd: (-3) cois.Rd:57: Lost braces
      57 | \item{No matter how the row names of the two matrices are arranged, as long as the row names are exactly the same; But we don't handle matrices with empty row names (the function will give an error).}
         |      ^
  checkRd: (-3) cois.Rd:60: Lost braces
      60 | \item{The two matrices can have different numbers of rows, but read our default handling carefully to make sure the calculation is accurate when using this function!!!}
         |      ^
  checkRd: (-3) hc.Rd:29: Lost braces
      29 | \item{(1). Input in a network of type "igraph" alone.}
         |      ^
  checkRd: (-3) hc.Rd:30: Lost braces
      30 | \item{(2). Must be entered as data frame or matrix with \code{subnet_mat2}.}
         |      ^
  checkRd: (-3) hc.Rd:35: Lost braces
      35 | \item{Try to make the rows of both matrices have the same attributes. Or we default:}
         |      ^
  checkRd: (-3) hc.Rd:36: Lost braces
      36 | \item{(1). If both matrices have row names, then the function counts all row names to produce two new matrices with the same row names.}
         |      ^
  checkRd: (-3) hc.Rd:37: Lost braces
      37 | \item{(2). If at most one matrix has row names, the function assigns new row names to both matrices on a row-to-row basis (any extra row names are assigned a new value) and then counts all row names to produce two new matrices with the same row names.}
         |      ^
  checkRd: (-3) hc.Rd:38: Lost braces
      38 | \item{The two matrices can have different numbers of rows, but read our default handling carefully to make sure the calculation is accurate when using this function!!!}
         |      ^
  checkRd: (-3) icmotif_count.Rd:31: Lost braces
      31 | \item{(1). Input in a network of type "igraph" alone.}
         |      ^
  checkRd: (-3) icmotif_count.Rd:32: Lost braces
      32 | \item{(2). Must be entered as data frame or matrix with \code{subnet_mat2}.}
         |      ^
  checkRd: (-3) icmotif_count.Rd:37: Lost braces
      37 | \item{Try to make the rows of both matrices have the same attributes. Or we default:}
         |      ^
  checkRd: (-3) icmotif_count.Rd:39: Lost braces
      39 | \item{When the two matrices can have different numbers of rows:}
         |      ^
  checkRd: (-3) icmotif_count.Rd:41: Lost braces
      41 | \item{(1). If both matrices have row names, then the function counts all row names to produce two new matrices with the same row names.}
         |      ^
  checkRd: (-3) icmotif_count.Rd:42: Lost braces
      42 | \item{(2). If at most one matrix has row names, the function assigns new row names to both matrices on a row-to-row basis (any extra row names are assigned a new value) and then counts all row names to produce two new matrices with the same row names.}
         |      ^
  checkRd: (-3) icmotif_count.Rd:45: Lost braces
      45 | \item{When the two matrices can have the same numbers of rows:}
         |      ^
  checkRd: (-3) icmotif_count.Rd:47: Lost braces
      47 | \item{No matter how the row names of the two matrices are arranged, as long as the row names are exactly the same; But we don't handle matrices with empty row names (the function will give an error).}
         |      ^
  checkRd: (-3) icmotif_count.Rd:50: Lost braces
      50 | \item{The two matrices can have different numbers of rows, but read our default handling carefully to make sure the calculation is accurate when using this function!!!}
         |      ^
  checkRd: (-3) icmotif_role.Rd:31: Lost braces
      31 | \item{(1). Input in a network of type "igraph" alone.}
         |      ^
  checkRd: (-3) icmotif_role.Rd:32: Lost braces
      32 | \item{(2). Must be entered as data frame or matrix with \code{subnet_mat2}.}
         |      ^
  checkRd: (-3) icmotif_role.Rd:37: Lost braces
      37 | \item{Try to make the rows of both matrices have the same attributes. Or we default:}
         |      ^
  checkRd: (-3) icmotif_role.Rd:39: Lost braces
      39 | \item{When the two matrices can have different numbers of rows:}
         |      ^
  checkRd: (-3) icmotif_role.Rd:41: Lost braces
      41 | \item{(1). If both matrices have row names, then the function counts all row names to produce two new matrices with the same row names.}
         |      ^
  checkRd: (-3) icmotif_role.Rd:42: Lost braces
      42 | \item{(2). If at most one matrix has row names, the function assigns new row names to both matrices on a row-to-row basis (any extra row names are assigned a new value) and then counts all row names to produce two new matrices with the same row names.}
         |      ^
  checkRd: (-3) icmotif_role.Rd:45: Lost braces
      45 | \item{When the two matrices can have the same numbers of rows:}
         |      ^
  checkRd: (-3) icmotif_role.Rd:47: Lost braces
      47 | \item{No matter how the row names of the two matrices are arranged, as long as the row names are exactly the same; But we don't handle matrices with empty row names (the function will give an error).}
         |      ^
  checkRd: (-3) icmotif_role.Rd:50: Lost braces
      50 | \item{The two matrices can have different numbers of rows, but read our default handling carefully to make sure the calculation is accurate when using this function!!!}
         |      ^
  checkRd: (-3) igraph_from_matrices.Rd:31: Lost braces
      31 | \item{Try to make the rows of both matrices have the same attributes. Or we default:}
         |      ^
  checkRd: (-3) igraph_from_matrices.Rd:33: Lost braces
      33 | \item{When the two matrices can have different numbers of rows:}
         |      ^
  checkRd: (-3) igraph_from_matrices.Rd:35: Lost braces
      35 | \item{(1). If both matrices have row names, then the function counts all row names to produce two new matrices with the same row names.}
         |      ^
  checkRd: (-3) igraph_from_matrices.Rd:36: Lost braces
      36 | \item{(2). If at most one matrix has row names, the function assigns new row names to both matrices on a row-to-row basis (any extra row names are assigned a new value) and then counts all row names to produce two new matrices with the same row names.}
         |      ^
  checkRd: (-3) igraph_from_matrices.Rd:39: Lost braces
      39 | \item{When the two matrices can have the same numbers of rows:}
         |      ^
  checkRd: (-3) igraph_from_matrices.Rd:41: Lost braces
      41 | \item{No matter how the row names of the two matrices are arranged, as long as the row names are exactly the same; But we don't handle matrices with empty row names (the function will give an error).}
         |      ^
  checkRd: (-3) igraph_from_matrices.Rd:44: Lost braces
      44 | \item{The two matrices can have different numbers of rows, but read our default handling carefully to make sure the calculation is accurate when using this function!!!}
         |      ^
  checkRd: (-3) node_cv.Rd:47: Lost braces
      47 | \item{(1). Input in a network of type "igraph" alone.}
         |      ^
  checkRd: (-3) node_cv.Rd:48: Lost braces
      48 | \item{(2). Must be entered as data frame or matrix with \code{subnet_mat2}.}
         |      ^
  checkRd: (-3) node_cv.Rd:53: Lost braces
      53 | \item{Try to make the rows of both matrices have the same attributes. Or we default:}
         |      ^
  checkRd: (-3) node_cv.Rd:55: Lost braces
      55 | \item{When the two matrices can have different numbers of rows:}
         |      ^
  checkRd: (-3) node_cv.Rd:57: Lost braces
      57 | \item{(1). If both matrices have row names, then the function counts all row names to produce two new matrices with the same row names.}
         |      ^
  checkRd: (-3) node_cv.Rd:58: Lost braces
      58 | \item{(2). If at most one matrix has row names, the function assigns new row names to both matrices on a row-to-row basis (any extra row names are assigned a new value) and then counts all row names to produce two new matrices with the same row names.}
         |      ^
  checkRd: (-3) node_cv.Rd:61: Lost braces
      61 | \item{When the two matrices can have the same numbers of rows:}
         |      ^
  checkRd: (-3) node_cv.Rd:63: Lost braces
      63 | \item{No matter how the row names of the two matrices are arranged, as long as the row names are exactly the same; But we don't handle matrices with empty row names (the function will give an error).}
         |      ^
  checkRd: (-3) node_cv.Rd:66: Lost braces
      66 | \item{The two matrices can have different numbers of rows, but read our default handling carefully to make sure the calculation is accurate when using this function!!!}
         |      ^
  checkRd: (-3) node_cv.Rd:34-35: Lost braces
      34 | \item{If \code{type} is either of "degree", "pagerank", "hub", "authority", "katz", "eigenvector", "closeness", the data frame has two columns, and the second column corresponds to either of "Degree", "Pagerank_versatility",
         |      ^
  checkRd: (-3) node_cv.Rd:36-37: Lost braces
      36 | \item{If \code{type} is "all", the data frame has eight columns, and columns form the second to the eighth correspond to "Degree", "Pagerank_versatility",
         |      ^
  checkRd: (-3) null_model.Rd:30: Lost braces
      30 | \item{For each of the four types of null models, there are corresponding algorithms. The first type, “subnetwork1”, involved scrambling the adjacency matrix of the first and second groups of the multilayer network.}
         |      ^
  checkRd: (-3) null_model.Rd:31: Lost braces
      31 | \item{The second type, “subnetwork2”, focused on scrambling the adjacency matrix of the second and third groups. }
         |      ^
  checkRd: (-3) null_model.Rd:32: Lost braces
      32 | \item{Comprehensively, the third type, “all”, blended the approaches of the first two to disarrange the entire network's adjacency matrix, achieving a thorough perturbation of the network's structure. }
         |      ^
  checkRd: (-3) null_model.Rd:33: Lost braces
      33 | \item{The last type named “Savue” that disarranged inherent structure in terms of the groups of species connected by each interconnecting species of every subnetworks, thus exhibiting different interconnection patterns.}}
         |      ^
  checkRd: (-3) pc.Rd:29: Lost braces
      29 | \item{(1). Input in a network of type "igraph" alone.}
         |      ^
  checkRd: (-3) pc.Rd:30: Lost braces
      30 | \item{(2). Must be entered as data frame or matrix with \code{subnet_mat2}.}
         |      ^
  checkRd: (-3) pc.Rd:35: Lost braces
      35 | \item{Try to make the rows of both matrices have the same attributes. Or we default:}
         |      ^
  checkRd: (-3) pc.Rd:36: Lost braces
      36 | \item{(1). If both matrices have row names, then the function counts all row names to produce two new matrices with the same row names.}
         |      ^
  checkRd: (-3) pc.Rd:37: Lost braces
      37 | \item{(2). If at most one matrix has row names, the function assigns new row names to both matrices on a row-to-row basis (any extra row names are assigned a new value) and then counts all row names to produce two new matrices with the same row names.}
         |      ^
  checkRd: (-3) pc.Rd:38: Lost braces
      38 | \item{The two matrices can have different numbers of rows, but read our default handling carefully to make sure the calculation is accurate when using this function!!!}
         |      ^
  checkRd: (-3) poc.Rd:29: Lost braces
      29 | \item{(1). Input in a network of type "igraph" alone.}
         |      ^
  checkRd: (-3) poc.Rd:30: Lost braces
      30 | \item{(2). Must be entered as data frame or matrix with \code{subnet_mat2}.}
         |      ^
  checkRd: (-3) poc.Rd:35: Lost braces
      35 | \item{Try to make the rows of both matrices have the same attributes. Or we default:}
         |      ^
  checkRd: (-3) poc.Rd:36: Lost braces
      36 | \item{(1). If both matrices have row names, then the function counts all row names to produce two new matrices with the same row names.}
         |      ^
  checkRd: (-3) poc.Rd:37: Lost braces
      37 | \item{(2). If at most one matrix has row names, the function assigns new row names to both matrices on a row-to-row basis (any extra row names are assigned a new value) and then counts all row names to produce two new matrices with the same row names.}
         |      ^
  checkRd: (-3) poc.Rd:38: Lost braces
      38 | \item{The two matrices can have different numbers of rows, but read our default handling carefully to make sure the calculation is accurate when using this function!!!}
         |      ^

0 errors ✔ | 0 warnings ✔ | 2 notes ✖
```

**Comment by WeichengSun** [comment]
Hi @adamhsparks, thank you, I have addressed these NOTEs, please continue to promote this issue.

**Comment by adamhsparks** [comment]
Thanks, @WeichengSun, 

1. I still see an issue with missing braces as shown here:

```r
  ✖ checking Rd files ... [0s/0s] NOTE checkRd: (-3)
    node_cv.Rd:34-35: Lost braces 34 | \item{If \code{type} is either
    of "degree", "pagerank", "hub", "authority", "katz", "eigenvector",
    "closeness", the data frame has two columns, and the second column
    corresponds to either of "Degree", "Pagerank_versatility", | ^
    checkRd: (-3) node_cv.Rd:36-37: Lost braces 36 | \item{If
    \code{type} is "all", the data frame has eight columns, and columns
    form the second to the eighth correspond to "Degree",
    "Pagerank_versatility", | ^
```

2. There is one other issue I'd like to have addressed. This doesn't appear to be a stats package, but you have SRR roclets. Could you please remove those as well as they are unnecessary and have already caused some confusion (mainly me being confused about this being a stats or normal package submission).

Thanks!

**Comment by WeichengSun** [comment]
OK @adamhsparks, I will continue to complete the issue, and I also accept your advice to put it on hold. Since this is only a tool for our scientific research, but our research work still needs to continue. Please inform me and provide other relevant requirements after you finish the working on a category for network standards. Thank you.
Mutual encouragement.

**Comment by maurolepore** [comment]
@WeichengSun FYI my EiC rotation just started. I see we're holding until https://github.com/ropensci/statistical-software-review-book/pull/67 is merged. I just asked for it's status at https://github.com/ropensci/statistical-software-review-book/pull/67#issuecomment-2629422637. Looking forward to continuing soon.

**Comment by maurolepore** [comment]
@WeichengSun I'm wrapping up my EiC rotation today and before I had it over to the next EiC I would like to ask if you could please write a few words explaining your intent and availability to resume. 

This might weight in the priority assigned to merging this issue: https://github.com/ropensci/statistical-software-review-book/pull/67

cc' @noamross andn @mpadge

**Comment by ldecicco-USGS** [comment]
Since this issue has been on hold longer than a year, I am going to close it. Please feel free to respond with new information if you'd like it reopened.

**Comment by mpadge** [comment]
Sorry @ldecicco-USGS and especially @WeichengSun, the ball is in my court on this one. I'll use your prompt to really endeavour to get the stats standards for network packages moving soon. Are you still interested?
